### ISSUE TITLE
macOS/build-locally instructions

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#101]
This is about fixing up the docs on building locally and/or find an easier way to run it on Mac where docker containers can't be used.

**Comment by camperdave** [comment]
I just installed this today on a mac. So far, there's not much to say - I used brew to ensure that I had the basics (xcode-based-compilers, wget, cmake, git, golang being the dependencies I recall adding), git cloned the repo and ran make build. The error messages returned were helpful to determine what was missing (cmake, for me) and it compiled with a similar degree of warnings as when I've done so in a linux docker container. Started the application up with `./local-ai --models-path=./models` Requests "ggml-gpt4all-j" work as expected - by default, the service is exposed to external devices on the network.

**Comment by antongisli** [comment]
I think this issue can be closed now @mudler , since we added instructions for building on mac?
maybe some of the dependencies that @camperdave mentions need to be added to the docs tho, but I suspect I had those already on my machine.

**Comment by soleblaze** [comment]
I'm getting a Mac Studio M2 Ultra this week. I'm currently planning on using it as a server. When I setup localai I'll create some instructions and put in a PR on localai-website.

**Comment by Aisuko** [comment]
Here is the document for building on macOS(M1 and M2) https://localai.io/basics/build/index.html#build-on-mac and it can also support Metal on macOS(check it at the bottom of that page). And it does not use docker and it has been tested by the community user. So, we can close this one now.
