### ISSUE TITLE
why does it dowload more than 5 gb when docker-compose up -d --pull always

### ISSUE THREAD

**Issue by TomiLikesToCode** [go-skynet/LocalAI#1033]
**LocalAI version:**

**Environment, CPU architecture, OS, and Version:**
windows 

**Describe the bug**
more than 5 gb download when docker-compose up -d --pull always
[+] Running 16/20                                                                                                        - api 19 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿⣿⣿⣿⣿⣀⣤] 1.009GB/6.226GB Pulling                                                   436.2s    ✔ 6a70103cc499 Pull complete                                                                                   73.5s    ✔ ccb4221e2c63 Pull complete                                                                                   75.0s    ✔ 9fe6e67e69c8 Pull complete                                                                                   81.5s    ✔ d4960566fad8 Pull complete                                                                                   87.7s    ✔ 75df79f77651 Pull complete                                                                                   99.9s    ✔ 2aea24d2c7fb Pull complete                                                                                  100.5s    ✔ 9869d4f923c5 Pull complete                                                                                  111.1s    ✔ 4f4fb700ef54 Pull complete                                                                                  111.7s    ✔ 9dd1feab6323 Pull complete                                                                                  120.2s    ✔ 5ab99a13851a Pull complete                                                                                  121.5s    ✔ e4ad34c52a9b Pull complete                                                                                  291.3s    - a61c3774c752 Downloading [======>                                            ]  61...                       430.8s    ✔ 217d59962b04 Download complete                                                                              138.0s    ✔ 882ee0fe5a87 Download complete                                                                              180.4s    ✔ e3ae11d966a3 Download complete                                                                              386.6s    ✔ 901d729ff20a Download complete                                                                              283.8s    ✔ 0ac0f771295e Download complete                                                                              287.7s    - 6808e50effb3 Downloading [=============>                                     ]  29...                       430.8s    - 69b28a994683 Downloading [=========================>                         ]  10...                       430.8s    - 6808e50effb3 Downloading    [========>                                          ] ...                       378.0s    - 69b28a994683 Pulling fs layer                                                            

**To Reproduce**
docker-compose up -d --pull always

**Expected behavior**
not downloading 1932954234892384823gb of files

**Logs**

**Additional context**

**Comment by lunamidori5** [comment]
You did not list the image you are downloading from the docker-compose file! But when you are running docker, you are spinning up a full on VM inside of your hosts layer 0. It has to download and set up the new OS for LocalAI to run in. If you have more questions or need help with a task feel welcomed to reach out on discord or make a new Issue and add me to the Assignees. Thank you <3
