### ISSUE TITLE
Example: Streamlit Bot with LocalAI

### ISSUE THREAD

**Issue by majoshi1** [go-skynet/LocalAI#1038]
## Streamlit bot

This is an example of a bot using Streamlit with LocalAI.
https://github.com/majoshi1/localai_streamlit_bot

![Screenshot](https://github.com/majoshi1/localai_streamlit_bot/blob/2b063c2145a6b795f62219066f680387059ecff7/streamlit-bot.png?raw=true)

**Comment by majoshi1** [comment]
Thanks @Aisuko for your reply. I cloned the repo, created a new local branch. But unable to push. Any idea?
```
$  git push --set-upstream origin streamlit-bot
remote: Permission to go-skynet/LocalAI.git denied to majoshi1.
fatal: unable to access 'https://github.com/go-skynet/LocalAI.git/': The requested URL returned error: 403
```

**Comment by Aisuko** [comment]
Hi @majoshi1. Jut `git push origin streamlit-bot`. And then create a PR on Github webpage by manually.

**Comment by majoshi1** [comment]
Thanks @Aisuko. I tried but getting same error. Any other option?
```
User@DESKTOP MINGW64 /c/opt/LocalAI (streamlit-bot)
$ git push origin streamlit-bot
remote: Permission to go-skynet/LocalAI.git denied to majoshi1.
fatal: unable to access 'https://github.com/go-skynet/LocalAI.git/': The requested URL returned error: 403
```
Please note that I had created `streamlit-bot` branch in my local. Is it ok?
```
git checkout -b streamlit-bot
```

**Comment by Aisuko** [comment]
Hi @majoshi1. Please fork localAI to your GitHub. And clone it to your local machine. Create a new branch and push it to the GitHub. And then create a PR from your repo to the localAI repo (which we called upstream repo).

**Comment by majoshi1** [comment]
Thanks @Aisuko. Did following steps:
-Forked LocalAI to my GitHub account.
-Created new branch.
-Cloned new branch to my local machine.
-Added example and updated examples readme.
-Pushed with a signed commit.
-Created a PR [1072](https://github.com/go-skynet/LocalAI/pull/1072) from my branch to upstream go-skynet/LocalAI repo.

Please check and get back in case of any questions.
