### ISSUE TITLE
Configuring `.gitignore` so `examples/chatbot-ui-manual/models` doesn't show in `git status`

### ISSUE THREAD

**Issue by jamesbraza** [go-skynet/LocalAI#1065]
When I make this repo a `git submodule` and then download a GGUF model to `examples/chatbot-ui-manual/models`, it shows up in my `git status`:

```
 ~/code/repo/LocalAI | on master > git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	examples/chatbot-ui-manual/models/llama-2-13b-chat.Q4_K_S.gguf
```

Can we configure this repo's `.gitignore` such that adding models to `examples/xyz/models` doesn't lead to a dirty `git status`?

**Comment by jamesbraza** [comment]
Looks like `examples/slack-bot` uses a symlink to `models/` to solve this problem.  It may be simplest to use the same symlink strategy in `examples/chatbot-ui`/`chatbot-ui-manual`

**Comment by jamesbraza** [comment]
Thank you @localai-bot, though Ideally the default of the `.gitignore` just works, no need to manually tweak it.

**Comment by Aisuko** [comment]
Hi @jamesbraza According to your comment. It looks like there is no issue. I'm going to close this issue now.

**Comment by jamesbraza** [comment]
@Aisuko I think you misinterpreted my response to the bot, this issue persists.  Can you reopen this?

This issue was about making the `.gitignore` apply to any `models/` directory in the repo

**Comment by jamesbraza** [comment]
@Aisuko opened a PR that will resolve this now, thanks for reopening!
