### ISSUE TITLE
Documentation of available build types

### ISSUE THREAD

**Issue by markuman** [go-skynet/LocalAI#1132]
Documentation sais

> ## Specify a build type. Available: cublas, openblas, clblas.
> BUILD_TYPE=cublas

But is there a missing **t** at the end of `clblas`?

So it must be `make BUILD_TYPE=clblast build`?

Is there a way to see if opencl is working propperly after build if finished?

**Comment by Aisuko** [comment]
Hi @markuman, thanks for your feedback. When you want to build LocalAI with `clblast`. You can follow the document directly. I have been checked the code, here you can see. It has `t` in the end of it.
https://github.com/go-skynet/LocalAI/blob/975387f7ae9f049be5ba8fb8a357e0484a17f55e/Makefile#L103C1-L105C6

So, do not worry about this. `clblas` It is a command of adding type to building process in Makefile. 

For the second question of `OpenCL`, here is a link maybe can help you. https://stackoverflow.com/questions/23121786/how-do-i-know-my-opencl-kernel-is-running-on-the-gpu

**Comment by Aisuko** [comment]
I am going to close this issue now but feel free to ask any question in here.
