### ISSUE TITLE
Template failed loading: template: prompt:1:8: executing "prompt" at <.RoleName>: can't evaluate field RoleName in type model.PromptTemplateData

### ISSUE THREAD

**Issue by yourtiger** [go-skynet/LocalAI#1151]
**LocalAI version:**

quay.io/go-skynet/local-ai:latest

**Environment, CPU architecture, OS, and Version:**

Linux localhost.localdomain 3.10.0-1160.99.1.el7.x86_64 https://github.com/go-skynet/LocalAI/issues/1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**

I user Llama2-chat-13B and use postman to ask questions。LocalAI error
![image](https://github.com/go-skynet/LocalAI/assets/9493473/b3ee6cdf-fffd-4921-be61-76bcb2d7e1b2)

**To Reproduce**

postman pic
![image](https://github.com/go-skynet/LocalAI/assets/9493473/04682922-fbac-430d-a3ae-85dff90d291f)

models folder
![image](https://github.com/go-skynet/LocalAI/assets/9493473/7e0ea521-1c03-42cb-bf15-39d231a8f351)

llama2.yaml
![image](https://github.com/go-skynet/LocalAI/assets/9493473/f7cfb835-5855-4740-9c52-0c0cf6afa7ee)

llama2-chat.tmpl
![image](https://github.com/go-skynet/LocalAI/assets/9493473/fb5ba468-6527-441a-8cef-c85c4b5e99d2)

llama2-completion.tmpl
![image](https://github.com/go-skynet/LocalAI/assets/9493473/99c8d48b-0c42-456e-be1e-fe7b4a9a5bdd)

**Expected behavior**

**Logs**

**Additional context**

**Comment by yourtiger** [comment]
https://localai.io/advanced/
Now I know the reason, if system_prompt is used in the template, then system_promptmust be defined in the yaml file of the model

**Comment by zenyanbo** [comment]
> https://localai.io/advanced/ 现在我知道原因了，如果模板中使用了system_prompt，那么system_prompt必须定义在模型的yaml文件中

Hello, I I also encountered this problem. It's shows `executing "prompt" at <.RoleName>: can't evaluate field RoleName in type model.PromptTemplateData`. My templ is 
```
<|im_start|>{{if eq .RoleName "assistant"}}assistant{{else if eq .RoleName "system"}}system{{else if eq .RoleName "user"}}user{{end}}
{{if .Content}}{{.Content}}{{end}}
<|im_end|>
```
How do you let it work? Can you provide me with your configuration file for reference? Thx

**Comment by yourtiger** [comment]
我不清楚LocalAI的模版是否支持RoleName，或者你写的格式。我参考的模版支持参数是https://localai.io/advanced/上的说明
我当时遇到的问题是，在我的模版中使用了system_prompt变量，但是没有在启动的llama2.yaml文件中定义system_prompt，所以，我只需要在llama2.yaml文件中增加system_prompt的说明如下：
![image](https://github.com/mudler/LocalAI/assets/9493473/d3d7b537-5430-4358-97a1-824ba2295be0)

**Comment by zenyanbo** [comment]
Oh, I see RoleName in your config llama2.yaml. So,  the error disappears after you add system_prompt, it means LocalAI support RoleName? I also saw similar jinja format in examples, but it report  an error as you.
