### ISSUE TITLE
Prompt template for ""https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf""

### ISSUE THREAD

**Issue by harshsing2891** [go-skynet/LocalAI#1181]
<!--  I  want to use below model while deploying localai using helm template so please provide sample of  values.yaml of helm including prompt template  for below model
"https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/resolve/main/llama-2-7b-chat.Q4_K_M.gguf"

**LocalAI version: latest

**Environment, CPU architecture, OS, and Version:**
kubernetes cluster v 1.24

**Comment by Aisuko** [comment]
You can check it from the model gallery https://localai.io/model-compatibility/llama-cpp/index.html

And the template is in here
https://github.com/go-skynet/model-gallery/blob/6d09a5aebfceb6253873230ee481b1d4269efa95/llama2-7b-chat-gguf.yaml#L39

**Comment by harshsing2891** [comment]
That template is not working with helm

**Comment by harshsing2891** [comment]
I have already check the provide link and it is not working with helm

**Comment by harshsing2891** [comment]
please reopen this issue

**Comment by harshsing2891** [comment]
I already tried prompt template available in mentioned link but with helm
it is not working.

**Comment by Aisuko** [comment]
Could you post some logs here?

**Comment by harshsing2891** [comment]
Hi ,

I am getting typical helm related issue the it cannot convert yaml into
json while using prompt template in values.yaml.

**Comment by harshsing2891** [comment]
I want to ask random questions to local ai and I m also expecting very
prompt response from local ai so please provide solutions including prompt
templates and values.yaml file for any llm based model

**Comment by harshsing2891** [comment]
i  want to use  huggingface ( open source models ) with localai   which does not require any key . Please provide sample values.yaml  of those models you have tested in kubernetes cluster which providing very quick response  of question like  "what is kuberneets cluster" ?
