### ISSUE TITLE
LocalAI do not support GPU

### ISSUE THREAD

**Issue by Aisuko** [go-skynet/LocalAI#1218]
### Discussed in https://github.com/go-skynet/LocalAI/discussions/1209

<div type='discussions-op-text'>

<sup>Originally posted by **kewaike** October 24, 2023</sup>
First of all, thank you very much for this great product.

I used docker-compose ，Build with CUDA，The compilation process is normal，but when LocalAI loads models ，Issue happend : 
CUDA：false

<img width="526" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/ca5b3ef8-6fb3-4e8d-9e5c-6e8b117f8a72">

<img width="1377" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/d2c94a2a-5ef6-4203-860c-0bb40874e22e">

Nvidia Driver and tookit are installed correctly，
.env file：
<img width="1195" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/c707c21f-b684-4e69-a456-fa0453113dcf">

docker-compose.yaml file：
<img width="450" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/e2b41961-1f32-443c-a9c5-9206a6e695f2">

in container ：
<img width="641" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/df0f0a9c-ef39-41f5-8d85-934e53b7e16c">

docker-compose.yaml file：
<img width="432" alt="image" src="https://github.com/go-skynet/LocalAI/assets/8566143/4d7087d5-aad6-40bf-b199-ddbd8bf68e6d">

System Information：
OS：CentOS7.9

I also installed stablediffusion （build，not docker），it works well with gpu .

 thanks </div>

**Comment by mudler** [comment]
@Aisuko - I moved this already to a discussion as it stands more for a support request rather than a bug. we have GPU tests, and manually using GPU just works.

**Comment by atljoseph** [comment]
So… which discussion was this moved to???

**Comment by Aisuko** [comment]
@atljoseph see https://github.com/mudler/LocalAI/discussions/1209

**Comment by atljoseph** [comment]
Thanks. I’ve already tried all those steps, and more. Outlined here:
https://github.com/mudler/LocalAI/discussions/2191. I’m sure other people
are running into this, and thus walking away from the project. This doesn’t
seem like a bug, though, but it does seem like something small that the
docs for LocalAI aren’t addressing. It’s a great repo and project and
community. I just can’t get it to run on my GPU from docker. Any help would
be much appreciated.

Planning to go and add more steps taken the past few days to try and get it
to recognize and offload to GPUs. Like, I can run a doctor image that
recognizes the devices, but when I run the LocalAI cuda 12 images, it
continues to use CPU only.

**Comment by atljoseph** [comment]
By the way, that link you provided does go to an issue. And on that issue and the subsequently linked issue, people have asked about a resolution. There has been no resolution. Please do not link a closed issue that has no resolution or helpful information, as it just makes things more confusing. if you want me to comment on those issues, they’re both closed.

**Comment by atljoseph** [comment]
I know you guys put a lot of work into this project, and I would like to use it. Please

**Comment by Aisuko** [comment]
https://github.com/mudler/LocalAI/discussions/2191

**Comment by Aisuko** [comment]
hi, @atljoseph thanks for your kind of words.

Have you check the document in here https://localai.io/features/gpu-acceleration/#cudanvidia-acceleration

I think you can check if the container can with gpu resources by following https://localai.io/docs/getting-started/run-other-models/#running-other-models

For example, `docker run -ti -p 8080:8080 --gpus all localai/localai:v2.13.0-cublas-cuda12 all-minilm-l6-v2` all-minim-l6-v2 is a 40 MB model for computing embeddings. It is easier for you to check the issue.

If the container can use GPUs resources. Your environment should OK. Then you can run any example which with GPU from localai website.

And from the log you post in discussion #2191 

`ModelFile:/models/Einstein-v6.1-Llama3-8B-Q4_K_M.gguf Device: UseTriton:false ModelBaseName: UseFastTokenizer:false PipelineType: SchedulerType: CUDA:false `

It means you are trying to use a CPU accelerate model(gguf), and you can also see you do not use CUDA. So, this is the reason I suggest you to run our GPU examples first.

**Comment by atljoseph** [comment]
It would be helpful to know why my model is CPU only. How did you know that
from looking at it? What steps should I take, other than the ones outlined
in the advanced usage and gpu accel docs? I succeeded in getting Cuda
equals true on the logs, but only after manually editing the model config.
The docs are very thorough, but there’s a lot missing in terms of basic
understanding. Like, what all goes in the configuration directory?
It is completely empty.
What is the most basic step for setting up the server configuration? I
can’t find anything to tell me what to put in there. Thank you

Thank you

**Comment by atljoseph** [comment]
Please impart some knowledge.

**Comment by atljoseph** [comment]
Finally got it to say CUDA true but after editing the model yaml. There is just so much configuration that it is blinding. It is still not offloading to gpu. Gguf is for cpu with ability to offload to gpu. Right? But hats what I’m trying to do.

**Comment by atljoseph** [comment]
When I exec into container nvidia smi command says same as outside container

**Comment by atljoseph** [comment]
If I’m having this much trouble, a lot of other people who are trying, this are having as much trouble

**Comment by atljoseph** [comment]
I’d be happy to contribute updates to the docs so that there are easier to read, if you could help me understand it better
