### ISSUE TITLE
never get response

### ISSUE THREAD

**Issue by antongisli** [go-skynet/LocalAI#131]
following the instructions from the README, for both the chat UI example or just with the curl example, I never get a response (or it is very slow - have been waiting for ten minutes now). M1 mac.

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/23321000/235355335-701b61c5-2319-4ad4-9740-32793b48e2de.png">

**Comment by mudler** [comment]
for Mac based on arm64 using docker will slow things down significantly, you need to build from source until we have #66

**Comment by mudler** [comment]
closing this, now we have instructions to run on mac, thanks @antongisli !
