### ISSUE TITLE
template for runpod.ai

### ISSUE THREAD

**Issue by fHachenberg** [go-skynet/LocalAI#155]
Hi there, I created a template for runpod.ai to spin up a local-ai server. It handles the download of models.
Might be interesting for you to mention or use for testing: https://runpod.io/gsc?template=uv9mtqnrd0&ref=984wlcra
Here's the source code for the image creation https://github.com/fHachenberg/local-ai-ootb

I originally based it on (your official?) image on quay.io but since it wasn't available anymore yesterday the dockerfile currently does the checkout and building. Probably not the best choice. I have only superficial knowledge of Docker, so let me know if I did something stupid. Thx a lot!

**Comment by mudler** [comment]
this is so cool @fHachenberg ! want to open up a PR to have it listed in our [examples](https://github.com/go-skynet/LocalAI/tree/master/examples)?

**Comment by fHachenberg** [comment]
#203

**Comment by mudler** [comment]
merged, closing. thanks @fHachenberg !

**Comment by kristoferlundgren** [comment]
@fHachenberg , @mudler:
Is it possible/feasible to use **LocalAI** in **RunPod's _serverless_** pods? I.e., per second billing.

I have looked but have not found any hints as to how I can run **LocalAI** in a scale-to-zero deployment where I can pay for CPU/GPU usage by the second, where API access would spin up LocalAI container(s) on-demand.
RunPod has the framework for this, but I'm not sure the current LocalAI container is prepared to run in this configuration.

Any hints are greatly appreciated!

**Comment by mudler** [comment]
> @fHachenberg , @mudler:
> Is it possible/feasible to use **LocalAI** in **RunPod's _serverless_** pods? I.e., per second billing.
> 
> I have looked but have not found any hints as to how I can run **LocalAI** in a scale-to-zero deployment where I can pay for CPU/GPU usage by the second, where API access would spin up LocalAI container(s) on-demand.
> RunPod has the framework for this, but I'm not sure the current LocalAI container is prepared to run in this configuration.
> 
> Any hints are greatly appreciated!

Last time I've tried it was enough to specify the cuda12 container image - Ive actually used that to test autogptq.

**Comment by kristoferlundgren** [comment]
> > @fHachenberg , @mudler:
> > Is it possible/feasible to use **LocalAI** in **RunPod's _serverless_** pods? I.e., per second billing.
> > I have looked but have not found any hints as to how I can run **LocalAI** in a scale-to-zero deployment where I can pay for CPU/GPU usage by the second, where API access would spin up LocalAI container(s) on-demand.
> > RunPod has the framework for this, but I'm not sure the current LocalAI container is prepared to run in this configuration.
> > Any hints are greatly appreciated!
> 
> Last time I've tried it was enough to specify the cuda12 container image - Ive actually used that to test autogptq.

Many thanks for the info @mudler !

I would suggest documenting the scale-to-zero use case so others know how to proceed, and that the possibility exists.

Again, thanks!
/Kristofer

**Comment by nblumoe** [comment]
@fHachenberg  did you take the docker image offline?
I tried using the template on runpod.io but got:

```
2024-11-28T18:11:58Z create container theveryomni/local-ai-ootb:latest
2024-11-28T18:12:00Z error pulling image: Error response from daemon: pull access denied for theveryomni/local-ai-ootb, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
2024-11-28T18:12:00Z error creating container: container: create: container create: Error response from daemon: No such image: theveryomni/local-ai-ootb:latest
```

Also the Github repo link gives me a 404.
