### ISSUE TITLE
Streaming mode?

### ISSUE THREAD

**Issue by apiad** [go-skynet/LocalAI#157]
Hi, thanks for this wonderful project!

Just wondering, are there any plans to support streaming mode? Maybe with a WebSocket endpoint? 

Right now, especially for long responses, the user has to wait for the full generation without any feedback. Even if we cannot reduce the inference time too much, an interactive response (via streaming) could alleviate significantly that sense of waiting for a response.

Thanks!

**Comment by mudler** [comment]
Hi @apiad ! 

This is currently in the works and tracked in #109 , currently on master it's already supported for `llama.cpp` models!

Closing this as it is a dup, but feel free to chime in #109 for anything.

**Comment by apiad** [comment]
Awesome, thanks!
