### ISSUE TITLE
examples/rwkv is missing the 'scripts' folder

### ISSUE THREAD

**Issue by jprobichaud** [go-skynet/LocalAI#197]
The docker file has:
```
WORKDIR /build
COPY ./scripts/ .
```
but tring to build the rwkv-converter, I get:
```Step 3/6 : WORKDIR /build
 ---> Using cache
 ---> 42df0f584a8b
Step 4/6 : COPY ./scripts/ .
COPY failed: file not found in build context or excluded by .dockerignore: stat scripts/: file does not exist```

Is there something obviously wrong?

**Comment by mudler** [comment]
oops right, thanks for opening up the issue. I didn't had committed here but I had it here locally - fixing it in #196 !

**Comment by jprobichaud** [comment]
thanks a ton!

**Comment by jprobichaud** [comment]
I can confirm that this works now!

**Comment by mudler** [comment]
> I can confirm that this works now!

awesome, thanks for the feedback @jprobichaud !
