### ISSUE TITLE
feat: add more test cases for the project and community maintenance

### ISSUE THREAD

**Issue by Aisuko** [go-skynet/LocalAI#262]
Hi, guys. I want to contribute to this project. I am familiar with the Golang language and the test framework this project is using.

Is it ok that I add some test cases for the projects? I saw here we use `ginkgo/v2` and `gomega` I am familiar with that style of test-cases development.

By the way, I have many years of open-source community maintenance experience. So, maybe I can help maintain the community, I mean not only contributing code. There are so many things like the works related to CI,  PR, creating labels, and classification for issues.

**Comment by mudler** [comment]
That sounds fantastic @Aisuko ! happy to have you onboard!

I really would appreciate the help, It has been mostly a solo-work up to now. 

Feel free to add tests, that'd be very much wanted as it is an area that needs improvement!

**Comment by Aisuko** [comment]
Thank you, It is my pleasure to contribute to the community.
