### ISSUE TITLE
suggestion to get AutoGTP approve PR

### ISSUE THREAD

**Issue by djdanielsson** [go-skynet/LocalAI#268]
Your readme says that you have an open PR with AutoGPT that would allow for that to work with this, that sounds amazing and would love to +1 it to try and help get that approved and merged faster along with the 3k other people who have starred, but there are over 250 open PR's to that repo so if you could provide a link in the readme to that PR that would be great.

**Comment by Aisuko** [comment]
Hi @djdanielsson I believe it is https://github.com/Significant-Gravitas/Auto-GPT/pull/2594#issue-1675672399

**Comment by mudler** [comment]
I've added an example on how to run autogpt here: https://github.com/go-skynet/LocalAI/tree/master/examples/autoGPT

I realized there is no need of any PR actually - it works already by setting the appropriate environment variables.
