### ISSUE TITLE
cannot unmarshal string into Go struct field OpenAIRequest.temperature of type float64" on windows?

### ISSUE THREAD

**Issue by MarcoLavoro** [go-skynet/LocalAI#273]
If I send this post request on the api endpoint I get as response:

{"error":{"code":500,"message":"failed reading parameters from request:json: cannot unmarshal string into Go struct field OpenAIRequest.temperature of type float64","type":""}}

Is a windows releated problem?

**Comment by Aisuko** [comment]
Hi, @MarcoLavoro , thanks for your feedback. Please show us more detail, like the prompt and your env information. It looks like the `temperature` cannot be "", it should be a float64 number.
