### ISSUE TITLE
feature: docker images with ffmpeg

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#281]

**Comment by ralyodio** [comment]
i would like too for video generation.

**Comment by sebastien-prudhomme** [comment]
@mudler  what is the legal issue that prevent installing ffmpeg?

**Comment by mudler** [comment]
the problem with ffmpeg is not the license per-se (LGPL/GPL) but rather that contains several codecs. IF you plan to use this commercially then it can be an issue, as patent owners of codecs algorithm, depending on country laws, can ask for license fee.  Since ffmpeg contains several codecs this turns out to be a problem. See also the ffmpeg license section: https://www.ffmpeg.org/legal.html

That's why having separate images with ffmpeg makes sense here - depending on the usage you do, you might or not want it in the images at all.
