### ISSUE TITLE
Switch back to prebuild Docker image by default

### ISSUE THREAD

**Issue by sebastien-prudhomme** [go-skynet/LocalAI#287]
Since #124, compilation is done on start.

I understand the need to have some kind of compatibility with old CPUs but I think having an image with prebuild application will be better for most use cases.

I propose to prebuild the application and allow in the entrypoint an option to rebuild or not the application on start.

The default behavior can be either to rebuild or not to rebuild.

**Comment by mudler** [comment]
good point, we could at least offer pre-compiled images as well
