### ISSUE TITLE
Error: Dimensionality of (384) does not match index dimensionality (1536) in LangChain-Chroma example

### ISSUE THREAD

**Issue by josh-s-g** [go-skynet/LocalAI#303]
Hello,
Firstly, what a great project :+1:

I'm trying the [langchain-chroma example](https://github.com/go-skynet/LocalAI/tree/master/examples/langchain-chroma) but having an issue running `query.py`:

```bash
  File ".../chromadb/db/index/hnswlib.py", line 123, in _check_dimensionality
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Dimensionality of (384) does not match index dimensionality (1536)
```

I can see from the Docker logs that `n_embd = 384` and `n_intermediate = 1536` for `bert` so I assume it has something to do with the embeddings, but I can't figure out what.

Any pointers on what this error might be? 

Thanks

**Comment by mudler** [comment]
in my case, this happened as well when switching embedding model while playing locally which gives different vector dimensions - I had to clean up the database storage and re-build the vector database.

**Comment by josh-s-g** [comment]
Thanks, is that a case of removing `persist_directory`, or are there also other things relating to the embedding model that are cached and need to cleaned up?

**Comment by mudler** [comment]
> Thanks, is that a case of removing `persist_directory`, or are there also other things relating to the embedding model that are cached and need to be cleaned up?

for me cleaning up the persistent directory was enough

**Comment by josh-s-g** [comment]
Right, thanks. I still have the error if I remove and recreate the vector database with `store.py`, but I'll see if a fresh `clone` of the project helps

**Comment by mudler** [comment]
@TylerGillson did you had the same issue here? I think you tried it very recently, right?

**Comment by josh-s-g** [comment]
I think you pointed me in the right direction - seems I was using the actual OpenAI API to create the embeddings rather than LocalAI. Re-cloning and following the instructions (especially env vars!) from the beginning did the trick, many thanks

**Comment by mudler** [comment]
> I think you pointed me in the right direction - seems I was using the actual OpenAI API to create the embeddings rather than LocalAI. Re-cloning and following the instructions (especially env vars!) from the beginning did the trick, many thanks

cool! glad you got it sorted, and thanks for the feedback!
