### ISSUE TITLE
Can you provide such a complete and interesting demonstration?

### ISSUE THREAD

**Issue by hktalent** [go-skynet/LocalAI#318]
# Can you provide such a complete and interesting demonstration?
###  Step 1, complete AI machine learning

In this step, I will input some address book information, which may be CSV or just other chaotic text. AI needs to automatically recognize, organize, and return which are people's names, addresses, or phone information, and learn and remember them

Then automatically save the learning results

### The ultimate goal is to achieve an AI search engine

**Comment by mudler** [comment]
Did you check the examples section? There is one exactly to address question answering on a dataset here: https://github.com/go-skynet/LocalAI/tree/master/examples/query_data

**Comment by rijalrojan** [comment]
@mudler 
I don't understand why OPENAI is necessary_ API_ KEY

We all hope to break away from the control of OpenAI

Can you tell me how to operate, use, and implement without the control of OpenAI?

**Comment by ralyodio** [comment]
it isnj't required, they just add it because you're supposed to be able to replace openai with this. leaving your code the same. you can either remove that or just set it to xyz.

**Comment by rijalrojan** [comment]
@ralyodio 

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from llama_index import SimpleDirectoryReader
from llama_index import Document
from llama_index.node_parser import SimpleNodeParser
from llama_index import GPTVectorStoreIndex



parser = SimpleNodeParser()


documents = SimpleDirectoryReader('data').load_data()

# 建立索引： 手动构建文档

text_list = ["老赖四川德阳市人：苏国欣（‭510602198003066833‬、成都保利花园二期武侯区聚贤街733号、鹭岛路33号22栋5单元502），做出执行依据单位： 成都市温江区人民法院
生效法律文书确定的义务： 苏国欣于本判决生效之日起十日内支付四川味道世家食品有限公司货款、库房租赁费共计405,789.5元及利息（2018年11月23日前的利息为128,904.75元；2018年11月24日以后的利息计算方式：以405,789.5元为基数，按月利率1%，自2018年11月24日起计算至实际清偿之日止）。如果未按本判决书指定的期间履行给付金钱义务，应当依照《中华人民共和国民事诉讼法》第二百六十条之规定，加倍支付迟延履行期间的债务利息。本案案件受理费10,626元，保全费3,933元，由苏国欣负担。如不服本判决，可以在判决书送达之日起十五日内，向本院递交上诉状，并按对方当事人或者代表人的人数提出副本，上诉于四川省成都市中级人民法院。本案判决生效后，负有履行义务的当事人应当依法按期履行。逾期未履行的，权利人申请执行后，人民法院依法对相关当事人采取限制高消费、列入失信名单、罚款、拘留等措施，构成犯罪的，依法追究刑事责任。"]
documents = [Document(t) for t in text_list]

#  节点
# nodes = parser.get_nodes_from_documents(documents)

# 索引
index = GPTVectorStoreIndex.from_documents(documents)
# index = GPTVectorStoreIndex(nodes)

query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)
```
