### ISSUE TITLE
where are the log files?

### ISSUE THREAD

**Issue by ralyodio** [go-skynet/LocalAI#325]
where are the log files for docker-compose -d?

**Comment by Aisuko** [comment]
Please check the official document here https://docs.docker.com/engine/reference/commandline/compose_logs/, thanks.

**Comment by Aisuko** [comment]
@ralyodio Hi, I saw you post the log, maybe we can close this issue?

**Comment by ralyodio** [comment]
I just removed the `-d` to keep logging in console. closing.
