### ISSUE TITLE
Adding GO_TAGS: stablediffusion to kubernetes causes pod to restart loop

### ISSUE THREAD

**Issue by lenaxia** [go-skynet/LocalAI#353]
Spawned off of #315 

**LocalAI version:**
1.14.1

**Environment, CPU architecture, OS, and Version:**
K3s 1.24
Flux
https://github.com/bjw-s/helm-charts/tree/main/charts

**Describe the bug**
Helm Release: https://github.com/lenaxia/home-ops-prod/blob/12a676aa0c09742c8426c972e49ea50102d09a5a/cluster/apps/home/localai/app/helm-release.yaml

**To Reproduce**
Helm install, see pod restart loop indefinitely

**Expected behavior**

**Logs**
https://pastebin.com/3yDrK4pW

**Additional context**
If I can get a reference to a working example I'd be happy to document what I'm missing or what is needed to get stable diffusion working.

**Comment by mudler** [comment]
Logs looks incomplete here, it ends up in the middle of building one of the backends

**Comment by lenaxia** [comment]
Here is the start of one of the restarts, as you can see, it just restarts the build process:

```
make -C go-llama clean
make[1]: Entering directory '/build/go-llama'
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I./llama.cpp -I. -O3 -DNDEBUG -std=c11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wno-unused-function -pthread -march=native -mtune=native
I CXXFLAGS: -I./llama.cpp -I. -I./llama.cpp/examples -I./examples -O3 -DNDEBUG -std=c++11 -fPIC -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -pthread
I LDFLAGS:
I BUILD_TYPE:  openblas
I CMAKE_ARGS:  -DLLAMA_BLAS=ON -DLLAMA_BLAS_VENDOR=OpenBLAS -DBLAS_INCLUDE_DIRS=/usr/include/openblas
I EXTRA_TARGETS:
I CC:       cc (Debian 10.2.1-6) 10.2.1 20210110
I CXX:      g++ (Debian 10.2.1-6) 10.2.1 20210110

rm -rf *.o
rm -rf *.a
make -C llama.cpp clean
make[2]: Entering directory '/build/go-llama/llama.cpp'
I llama.cpp build info:
I UNAME_S:  Linux
I UNAME_P:  unknown
I UNAME_M:  x86_64
I CFLAGS:   -I.              -O3 -std=c11   -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -pthread -march=native -mtune=native
I CXXFLAGS: -I. -I./examples -O3 -std=c++11 -fPIC -DNDEBUG -Wall -Wextra -Wpedantic -Wcast-qual -Wno-unused-function -Wno-multichar -pthread -march=native -mtune=native
I LDFLAGS:
I CC:       cc (Debian 10.2.1-6) 10.2.1 20210110
I CXX:      g++ (Debian 10.2.1-6) 10.2.1 20210110
...
```

I've also upgraded the initContainer to pre-populate the stablediffusion model files before it starts building and it still doesn't seem to take. 

https://github.com/lenaxia/home-ops-prod/blob/ccc3da0ed701f7dd08e370674ac330816d4c74db/cluster/apps/home/localai/app/helm-release.yaml

@mudler can you just provide a full `kubectl describe` of your `deployment/localai`? That will help me see what else is different.

**Comment by sebastien-prudhomme** [comment]
@lenaxia you may need to configure the default liveness probe to your compilation time: https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml#L233

**Comment by mudler** [comment]
@lenaxia are you using the LocalAI charts? https://github.com/go-skynet/LocalAI#run-localai-in-kubernetes

**Comment by lenaxia** [comment]
@sebastien-prudhomme it's always something royally stupid. Yes it was the readiness probes. Thanks, it at least built.

@mudler No, I wasn't using the chart, I'm using the common app-template that the Kubernetes@home has adopted as standard best practice which provides a lot of benefits for free such as extensible volume mounts, and others. Sebastian's pointer to the readiness probes was the key for the build issue, however I'm now hitting a segfault.

I'll start a new issue for that.
