### ISSUE TITLE
feature: constrained grammars

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#354]
**Is your feature request related to a problem? Please describe.**
Output of valid JSON, YAML, or alikes from a model is challenging. Models hallucinates, prompts needs to be fine-tuned, and there is no guarantee it spits valid output format.

**Describe the solution you'd like**
A way to constrain the output with a grammar. Ideally, would be great to have here as an endpoint this https://twitter.com/GrantSlatton/status/1660348210605596672 - https://github.com/grantslatton/llama.cpp/commit/007e26a99d485007f724957fa8545331ab8d50c3 .

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by kcarnold** [comment]
Related existing solution https://github.com/microsoft/guidance/

**Comment by lee-b** [comment]
See also: https://github.com/1rgs/jsonformer

I think there are probably two ways to accomplish this:

1) At the prompt/output level, generating all of the syntax between values as a prompt, then prompting for only the value, and cutting off the response when a syntactically incorrect token is generated, and so on. Pro: should work with any model / implementation.  Con: while it should never generate invalid json, it probably generates empty json that might need to be thrown away at a higher-level json schema checker.

2) at the sampler level, with knowledge of the desired syntax, so adjusting the likelihood of generating a particular token. Benefit: should work much more reliably, with true syntax awareness.  Con: is probably limited to one NN architecture/SDK, like pytorch.

Both approaches have pros and cons, and both require significant effort in parsing syntax.

JSONFormer appears to be the latter, better approach, but also refers to other implementations that seem to do the former.

**Comment by mudler** [comment]
I can share some updates very soon - I got it working with the llama.cpp PR which adds constrained grammars ( I don't have the link now). I could successfully implement OpenAI functions. Will follow up shortly with my experiments

**Comment by mudler** [comment]
When `llama.cpp` is going to merge this PR: https://github.com/ggerganov/llama.cpp/pull/1773 constrained grammar output will be unblocked and quite easy to implement. I've hacked my way today something, will cleanup and push in a branch soon.
