### ISSUE TITLE
issue with rwkv examples

### ISSUE THREAD

**Issue by chkp-ofirs** [go-skynet/LocalAI#401]
**LocalAI version:**  v1.16.0

**Environment, CPU architecture, OS, and Version:** VM, Linux 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
The rwkv examples fail.
It use Q4_2 (build.sh: python3 /build/rwkv.cpp/rwkv/quantize.py /build/float-model $OUT Q4_2
), rwkv.cpp drop Q4_2 support [master-dea929f](https://github.com/saharNooby/rwkv.cpp/releases/tag/master-dea929f) 

**To Reproduce**
cd ~/LocalAI/examples/rwkv# docker build -t rwkv-converter -f Dockerfile.build .

**Expected behavior**

**Logs**
+ python3 /build/rwkv.cpp/rwkv/quantize.py /build/float-model /data/models/rwkv Q4_2
usage: quantize.py [-h] src_path dest_path {Q4_0,Q4_1,Q5_0,Q5_1,Q8_0}
quantize.py: error: argument format_name: invalid choice: 'Q4_2' (choose from 'Q4_0', 'Q4_1', 'Q5_0', 'Q5_1', 'Q8_0')

**Additional context**

**Comment by mudler** [comment]
rwkv.cpp just yesterday updated its format with the latest ggml changes which makes models incompatible: https://github.com/saharNooby/rwkv.cpp/commit/dea929f8cad90b7cf2f820c5a3d6653cfdd58c4e . I'm updating RWKV in #402 , meanwhile, you can use an older version of rwkv to quantize models, or use the LocalAI version from that branch.
