### ISSUE TITLE
feature: Enable token stream on /completion

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#406]
**Is your feature request related to a problem? Please describe.**
Currently, `stream: true` is honored only with the `/chat/completion` endpoint

**Describe the solution you'd like**
The `/completion` endpoint should support it as well

**Describe alternatives you've considered**

**Additional context**

**Comment by krishnaduttPanchagnula** [comment]
@mudler  do you mean on the following endpoint:

app.Post("/**completions**", completionEndpoint(cm, options))

**Comment by mudler** [comment]
closing dup of #416

**Comment by EchedeyLR** [comment]
This is currently causing memory issues with requests using that option.

Models work in my 16 GiB of RAM with single POST requests without that enabled, but not with that one...
