### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dillfrescott** [go-skynet/LocalAI#42]
Error: initializing source docker://quay.io/go-skynet/local-api:latest: reading manifest latest in quay.io/go-skynet/local-api: unauthorized: access to the requested resource is not authorized

**Comment by mudler** [comment]
Hey @dillfrescott ! :wave: 

where did you found the image name? there seems to be a typo, should be quay.io/go-skynet/local-ai instead of quay.io/go-skynet/local-api
