### ISSUE TITLE
Make build fails at $(GOCMD) mod download

### ISSUE THREAD

**Issue by intermag0** [go-skynet/LocalAI#457]
**LocalAI version:**
1.17.1

**Environment, CPU architecture, OS, and Version:**
MINGW64_NT-10.0-19044 DESKTOP-HSTM119 3.3.6-bec3d608-341.x86_64 2023-02-22 08:29 UTC x86_64 Msys

**Describe the bug**
Make build fails at $(GOCMD) mod download (go-rwkv)

This is happening for go-rwkv
![image](https://github.com/go-skynet/LocalAI/assets/133572171/a00290fc-932b-4bcd-b3fb-a9c7267df7b2)

go.mod file for go-rwkv
![image](https://github.com/go-skynet/LocalAI/assets/133572171/d5b8daa2-2bf5-44eb-af4a-a26433aa3f9f)

main go.mod file (after replace: is run)
![image](https://github.com/go-skynet/LocalAI/assets/133572171/d3c22cc1-278c-47ce-92c6-8b61736867e5)

**To Reproduce**
Just run make build

**Expected behavior**

**Logs**

**Additional context**
I would like to run without docker.
Downloaded MINGW64 & Go, not sure if there is any other dependencies
Working folder is C:\Projects\LocalAI

**Comment by Aisuko** [comment]
Hi, @intermag0. I believe you are trying to build the project on Windows without using container. The Makefile contains many of shell scripts may do not support by windows platform. I suggest you build the it in container environment. And here is our document for supporting the windows https://localai.io/basics/build/#windows-compatibility
