### ISSUE TITLE
chatGML Model compatibility

### ISSUE THREAD

**Issue by guotao** [go-skynet/LocalAI#515]
**Is your feature request related to a problem? Please describe.**

 Great job , but would LocalAI add support for chatGML which has better Chinese support? Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Aisuko** [comment]
Hi @guotao, thanks for your suggestion. If `ggml` supports chatGML model, I believe LocalAI may support it too.

**Comment by Aisuko** [comment]
Repeat with #754 close this one.
