### ISSUE TITLE
Expose prometheus metrics

### ISSUE THREAD

**Issue by mrueg** [go-skynet/LocalAI#519]
**Is your feature request related to a problem? Please describe.**

Currently it's difficult to track how localAI is used and if it's working. It would be good to have metrics on response times as well as errors.  https://sre.google/sre-book/monitoring-distributed-systems/

**Describe the solution you'd like**
Have a /metrics endpoint that exposes https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md

**Describe alternatives you've considered**
Exporting metrics via json_exporter

**Additional context**
-

**Comment by mudler** [comment]
Hey @mrueg :wave: 

nice to see you again! That sounds like a great addition, definitely something we want to add.

**Comment by sebastien-prudhomme** [comment]
OpenTelemetry is another option. You could have both metrics (compatible with OpenMetrics with a Prometheus exporter) and traces.

**Comment by soleblaze** [comment]
OTel is becoming the new defacto way to do it. I’ve been wanting a project where I can set this up. I’ll take a look at this sometime in the next week. Need to setup an environment to ingest them first.

**Comment by jespino** [comment]
I have an initial setup for adding metrics using OpenTelemetry. I'm limiting it to the bare minimum to introduce only what is needed for expose prometheus metrics, in the future we can expand that to add traces. What kind of metrics would you like to add there? The default Go metrics are there, but what would you consider interesting to include?
