### ISSUE TITLE
Cors Problem Using JS Axios

### ISSUE THREAD

**Issue by Andreh1982** [go-skynet/LocalAI#585]
Excuse me, hello! 

I'm facing a issue using a JS front-end to connect to the LocalAI API. I saw the issue about the Cors fix, but it still doesn't work. 

I also tried to disable cors in axios, but with that option i cant retrieve the body response.

Axios Function(i'm a newbie, please be nice <3)

`function StartShowPayload() {
  const [payload, setPayload] = useState([]);
  useEffect(async () => {
    axios.get("http://192.168.2.32:8080/models", ).then((res) => {
      const threads = res;
      setPayload(threads);
    });
  }, []);`
  
  LocalAI API is running in another computer inside my local network, Thank you so much for your time! :)

**Comment by mike-niemand** [comment]
You can set corsAllowedOrigins in the .env

**Comment by Andreh1982** [comment]
Hey Mike, thank you! Should i set, like:

corsAllowedOrigins = "*"

Or

CORSALLOWEDORIGINS = "*"

?

**Comment by mike-niemand** [comment]
I've used the first but I've set it explicitly. Setting wildcards can creep
into production. Look at api.go and you can see how this is implemented.

**Comment by greyhammer** [comment]
Did you ever get this sorted?
