### ISSUE TITLE
Possible to use it without docker?

### ISSUE THREAD

**Issue by coldcode69** [go-skynet/LocalAI#6]
Would really appreciate some instructions or guidance for getting this working directly, without docker. I noticed it's using a modified llama.cpp mixed with golong, but I don't have enough knowledge with this to build it. I did try building it but got a error about lama.h not being found.

**Comment by mudler** [comment]
good point, I'll have a look as soon as possible.

**Comment by mkellerman** [comment]
You can try and copy my Makefile from here: https://github.com/go-skynet/llama-cli/blob/ad18b8305449b54f63383408bc47c246cacdf419/Makefile

If you have all the required GO dependancies, you can use `make build` and `make run` to run it on your machine directly.

**Comment by mkellerman** [comment]
@mudler if this Makefile is tested and merged, then we could close this issue?

(we could make it a seperate PR if you wish)

**Comment by mkellerman** [comment]
you should now be able to do 'make build' if you use latest and have all the required dependancies (ie: go, cmake).

@mudler i think we can close this item.

We would need to update the documentation tho, so this issue doesn't re-apead for lack of docs.

**Comment by limcheekin** [comment]
I don't have experience in GoLang. Currently I have a question answering chatbot developed using LangChain Python and hosted as AWS Lambda function. 

I want to swap out the OpenAI API dependency to LocalAI if possible.  Appreciate your advise whether it is feasible to do so and please share the steps on how to do so.

Thanks in advanced.

**Comment by mudler** [comment]
> I don't have experience in GoLang. Currently I have a question answering chatbot developed using LangChain Python and hosted as AWS Lambda function. You may want to look into the github repo at https://github.com/limcheekin/serverless-flutter-gpt.
> 
> I want to swap out the OpenAI API dependency to LocalAI if possible. Appreciate your advise whether it is feasible to do so and please share the steps on how to do so.
> 
> Thanks in advanced.

@limcheekin :wave: feel free to join our Discord channel, however I think it should be as simple as specifying from the OpenAI client you already use a different base_url, and point it to where the API runs.

**Comment by mudler** [comment]
I'm closing this issue now, as building locally should be possible with `make build`. I've opened https://github.com/go-skynet/LocalAI/issues/66 to track having binary releases
