### ISSUE TITLE
Chatting with StarChat does not produce an output

### ISSUE THREAD

**Issue by mads-oestergaard** [go-skynet/LocalAI#605]
**LocalAI version:**

Running container image `quay.io/go-skynet/local-ai:latest` with the docker-compose.yaml from master (commit 295f3030a9f76f7f36705abb760a2cd351d2b4d8)

**Environment, CPU architecture, OS, and Version:**

`Linux hostname 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Describe the bug**

With StarChat Beta, a instruct finetuned starcoder, I cannot get responses through the API.

The output of does not appear to be parsed correctly; there is no content in the reply: 
```
user@hostname:~/LocalAI$ curl localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
    "model": "gpt-3.5-turbo", 
    "messages": [ {"role":"user", "content":"how do i sort a list in python?"} ]
    }' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   264  100   164  100   100     13      8  0:00:12  0:00:11  0:00:01    46
{
  "object": "chat.completion",
  "model": "gpt-3.5-turbo",
  "choices": [
    {
      "message": {
        "role": "assistant"
      }
    }
  ],
  "usage": {
    "prompt_tokens": 0,
    "completion_tokens": 0,
    "total_tokens": 0
  }
}
```

**To Reproduce**

Download one of the ggml starchat beta models:
`$ wget https://huggingface.co/TheBloke/starchat-beta-GGML/resolve/main/starchat-beta.ggmlv3.q4_1.bin -O models/starchat-beta-q4_1.ggmlv3`

`$ touch models/gpt-3.5-turbo.yaml`
Insert this config in gpt-3.5-turbo.yaml
```yaml
name: gpt-3.5-turbo
# Default model parameters
parameters:
  # Relative to the models path
  model: starchat-beta-q4_1.ggmlv3
backend: starcoder
context_size: 8192
threads: 4
debug: true
template:
  chat: chat
stopwords:
- <|end|>
```

Create a chat.tmpl file and add this to it:
```
<|system|> Below is a conversation between a human user and a helpful AI coding assistant. <|end|> 
<|user|> {{.Input}} <|end|>
<|assistant|>
```

Call the 

**Expected behavior**

I would expect the response to contain something like this, generated from the demo on https://huggingface.co/HuggingFaceH4/starchat-beta:
_There are multiple ways to sort a list in Python. One of the most common ways is to use the sort() method. Here is an example:_

```
my_list = [3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5]
my_list.sort()
print(my_list)
```

_This will sort the list in place and print the sorted list._

**Logs**

```
api_1  | Starting LocalAI using 4 threads, with models path: /models
api_1  | 7:23AM DBG Model: gpt-3.5-turbo (config: {OpenAIRequest:{Model:starchat-beta-q4_1.ggmlv3 File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0 TopK:0 Temperature:0 Maxtokens:0 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 Seed:0 Mode:0 Step:0} Name:gpt-3.5-turbo StopWords:[<|end|>] Cutstrings:[] TrimSpace:[] ContextSize:8192 F16:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend:starcoder TemplateConfig:{Completion: Chat:chat Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:false MMlock:false TensorSplit: MainGPU: ImageGenerationAssets: PromptCachePath: PromptCacheAll:false PromptCacheRO:false PromptStrings:[] InputStrings:[] InputToken:[]})
api_1  | 7:23AM DBG GPT4ALL_IMPLEMENTATIONS_PATH: /tmp/localai/backend_data/backend-assets/gpt4all
api_1  | 
api_1  |  ┌───────────────────────────────────────────────────┐ 
api_1  |  │                   Fiber v2.46.0                   │ 
api_1  |  │               http://127.0.0.1:8080               │ 
api_1  |  │       (bound on host 0.0.0.0 and port 8080)       │ 
api_1  |  │                                                   │ 
api_1  |  │ Handlers ............ 24  Processes ........... 1 │ 
api_1  |  │ Prefork ....... Disabled  PID ............... 209 │ 
api_1  |  └───────────────────────────────────────────────────┘ 
api_1  | 
api_1  | 7:23AM DBG Request received: {"model":"gpt-3.5-turbo","file":"","language":"","response_format":"","size":"","prompt":null,"instruction":"","input":null,"stop":null,"messages":[{"role":"user","content":"how do i sort a list in python?"}],"stream":false,"echo":false,"top_p":0,"top_k":0,"temperature":0,"max_tokens":0,"n":0,"batch":0,"f16":false,"ignore_eos":false,"repeat_penalty":0,"n_keep":0,"mirostat_eta":0,"mirostat_tau":0,"mirostat":0,"frequency_penalty":0,"tfz":0,"seed":0,"mode":0,"step":0}
api_1  | 7:23AM DBG Parameter Config: &{OpenAIRequest:{Model:starchat-beta-q4_1.ggmlv3 File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0 TopK:0 Temperature:0 Maxtokens:0 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 Seed:0 Mode:0 Step:0} Name:gpt-3.5-turbo StopWords:[<|end|>] Cutstrings:[] TrimSpace:[] ContextSize:8192 F16:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend:starcoder TemplateConfig:{Completion: Chat:chat Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:false MMlock:false TensorSplit: MainGPU: ImageGenerationAssets: PromptCachePath: PromptCacheAll:false PromptCacheRO:false PromptStrings:[] InputStrings:[] InputToken:[]}
api_1  | 7:23AM DBG Template found, input modified to: <|system|> Below is a conversation between a human user and a helpful AI coding assistant. <|end|> 
api_1  | <|user|> how do i sort a list in python? <|end|>
api_1  | <|assistant|>
api_1  | 7:23AM DBG Loading model starcoder from starchat-beta-q4_1.ggmlv3
api_1  | 7:23AM DBG Loading model in memory from file: /models/starchat-beta-q4_1.ggmlv3
api_1  | [172.30.0.1]:38790  200  -  POST     /v1/chat/completions
api_1  | 7:23AM DBG Response: {"object":"chat.completion","model":"gpt-3.5-turbo","choices":[{"message":{"role":"assistant"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```

**Additional context**

**Comment by luoweb** [comment]
Is this issue solved?

**Comment by mads-oestergaard** [comment]
Yes, I see the same thing. If you modify the template to "<|system|>\n<|end|>\n<|user|>{{.Input}} <|end|>\n<|assistant|>" similar to the example in https://huggingface.co/HuggingFaceH4/starchat-beta, see the code block, then there is still no output: 

```
api_1  | 7:57AM DBG Parameter Config: &{OpenAIRequest:{Model:starchat-beta-q4_1.ggmlv3 File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0 TopK:0 Temperature:0 Maxtokens:0 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 Seed:0 Mode:0 Step:0 TypicalP:0} Name:starchat StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:8192 F16:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend:starcoder TemplateConfig:{Completion: Chat:chat Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:false MMlock:false LowVRAM:false TensorSplit: MainGPU: ImageGenerationAssets: PromptCachePath: PromptCacheAll:false PromptCacheRO:false PromptStrings:[] InputStrings:[] InputToken:[]}
api_1  | 7:57AM DBG Template found, input modified to: <|system|>
api_1  | <|end|> 
api_1  | <|user|> how do i sort a list in python? <|end|>
api_1  | <|assistant|>
api_1  | 7:57AM DBG Loading model starcoder from starchat-beta-q4_1.ggmlv3
api_1  | 7:57AM DBG Loading model in memory from file: /models/starchat-beta-q4_1.ggmlv3
api_1  | 7:57AM DBG Response: {"object":"chat.completion","model":"starchat","choices":[{"message":{"role":"assistant"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
api_1  | [10.4.80.103]:47196  200  -  POST     /v1/chat/completions
```

I suspect it has something to do with the stop-token.

**Comment by luoweb** [comment]
> Yes, I see the same thing. If you modify the template to "<|system|>\n<|end|>\n<|user|>{{.Input}} <|end|>\n<|assistant|>" similar to the example in https://huggingface.co/HuggingFaceH4/starchat-beta, see the code block, then there is still no output:
> 
> ```
> api_1  | 7:57AM DBG Parameter Config: &{OpenAIRequest:{Model:starchat-beta-q4_1.ggmlv3 File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0 TopK:0 Temperature:0 Maxtokens:0 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 Seed:0 Mode:0 Step:0 TypicalP:0} Name:starchat StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:8192 F16:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend:starcoder TemplateConfig:{Completion: Chat:chat Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:false MMlock:false LowVRAM:false TensorSplit: MainGPU: ImageGenerationAssets: PromptCachePath: PromptCacheAll:false PromptCacheRO:false PromptStrings:[] InputStrings:[] InputToken:[]}
> api_1  | 7:57AM DBG Template found, input modified to: <|system|>
> api_1  | <|end|> 
> api_1  | <|user|> how do i sort a list in python? <|end|>
> api_1  | <|assistant|>
> api_1  | 7:57AM DBG Loading model starcoder from starchat-beta-q4_1.ggmlv3
> api_1  | 7:57AM DBG Loading model in memory from file: /models/starchat-beta-q4_1.ggmlv3
> api_1  | 7:57AM DBG Response: {"object":"chat.completion","model":"starchat","choices":[{"message":{"role":"assistant"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
> api_1  | [10.4.80.103]:47196  200  -  POST     /v1/chat/completions
> ```
> 
> I suspect it has something to do with the stop-token.

I was succeeded on Mac OS by the following tmpl:
```yaml
{{.Input}} <|end|>
<|assistant|>
```

**Comment by Aisuko** [comment]
It looks like the issue can be fixed by using the prompt template as @luoweb mentioned above. I am going to close this issue now. Please free to open it if the issue still occurs.
