### ISSUE TITLE
chatbot-ui fetching models with POST gets 405 - Method not allowed

### ISSUE THREAD

**Issue by marpanda00** [go-skynet/LocalAI#607]
/

**LocalAI version:commit 295f3030a9f76f7f36705abb760a2cd351d2b4d8

**Environment, CPU architecture, OS, and Version :Linux pipeline-358962 4.14.177-139.254.amzn2.x86_64 #1 SMP Thu May 7 18:48:23 UTC 2020 x86_64 GNU/Linux

**Describe the bug**
call from chatbot-ui to retrieve the list of models with a POST gets "405 - Method not allowed"

curl http://localhost:8080/v1/models -H "Content-Type: application/json" -d '{ }'                          

Expected list of models

[127.0.0.1]:48430  405  -  POST     /v1/models

**Additional context**
chatbot-ui pulled the latest version "commit fa3f6e93bbe0d1ff9f208ddefae6fc7dfb738dc7"

**Comment by mike-niemand** [comment]
Isn't this a GET?
