### ISSUE TITLE
Docker Container not working on Windows WSL and also not on Windows10

### ISSUE THREAD

**Issue by SwannSchilling** [go-skynet/LocalAI#655]
I followed the installation instructions step by step and I am still getting

standard_init_linux.go:228: exec user process caused: no such file or directory

also fixed the line endings of the Dockerfile, but still...

I tried
docker build -t localai .
docker run localai

and also
docker-compose up -d --pull always

( the --pull always is also not working for me)

If I install in WSL the model path is not being recognized.
I tried to make build on Windows, but it keeps throwing errors at me...if there is a detailed guide on how to build for Windows or a Docker Container for Windows it would be highly appreciated!

The Docker Container on Ubuntu Jammy Jellyfish works flawless, but Windows is my main machine...

**Comment by Aisuko** [comment]
For the first issue, I am guessing it may be related to CRLF, please take a look to get more detail https://github.com/opensemanticsearch/open-semantic-search/issues/427

For the second one, please do more investigations I assume it should be working well https://github.com/docker/compose/pull/10128

**Comment by SwannSchilling** [comment]
Thanks a lot! I will try that!

**Comment by Aisuko** [comment]
Feel free to reopen the issue if it is not solved.
