### ISSUE TITLE
feature: binary releases

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#66]
Now that we eased out building locally, we could as well release generic binary and optimized ones for the various platform we support

**Comment by mudler** [comment]
Binary releases are available now: https://github.com/go-skynet/LocalAI/releases/tag/v1.15.0

**Comment by geoman2** [comment]
Hello Ettore, any chances to see LocalAI released as wasm module, do not know how/where to open a pull request so asked here.
