### ISSUE TITLE
multi-character unicode is mangled in streaming mode

### ISSUE THREAD

**Issue by samm81** [go-skynet/LocalAI#677]
**LocalAI version:**
cc31c58235496ad7b703b55096172efb1e37feb8

**Environment, CPU architecture, OS, and Version:**
`Linux 6.1.31_1 #1 SMP PREEMPT_DYNAMIC Wed May 31 05:53:37 UTC 2023 x86_64 GNU/Linux`

**Describe the bug**
emojis, and I assume all multi-character emoji, are sent as multiple messages of `\ufffd`, aka the [replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) (�) .

**To Reproduce**
```
❯ curl -N http://localhost:57541/v1/completions -H "Content-Type: application/json" -d '{
     "model": "ggml-model-q4_0.bin",
     "prompt": "",
     "max_tokens": 32,
     "temperature": 0.7,
     "stream": true
   }'
data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"\ufffd"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"\ufffd"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"\ufffd"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"\ufffd"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":" |"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":" I"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"'"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

data: {"object":"text_completion","model":"ggml-model-q4_0.bin","choices":[{"text":"m"}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```

**Expected behavior**
the emoji sent is supposed to be 😂, which, I think ? , should be [U+1F602](https://emojipedia.org/emoji/%F0%9F%98%82/) . I'm not 100% sure how that should be chunked for streaming purposes.

**Logs**

**Additional context**
I only test the `/completions` endpoint, I don't know if this also doesn't work for other endpoints.

**Comment by Tengxu666** [comment]
Do you have any gzip related errors when running docker-compose startup

**Comment by samm81** [comment]
> Do you have any gzip related errors when running docker-compose startup

no - but I'm not using `docker compose` I'm just building & running the container manually

**Comment by samm81** [comment]
> Do you have any gzip related errors when running docker-compose startup

after rebasing onto d3a486a4f8f9d73677119ca8207161f03a015fd3 I'm now seeing this issue: https://github.com/go-skynet/LocalAI/issues/662#issuecomment-1607846043

**Comment by yarray** [comment]
Observed the same behavior. I used `docker compose` and did not see gzip-related error. The issue broke chats in Chinese.

**Comment by samm81** [comment]
#662 has been resolved, but this issue is still happening

**Comment by llllvvuu** [comment]
For non-Roman languages, my process crashes altogether.

I am using `llama-2-7b-chat.ggmlv3.q4_0.bin` with `prompt-templates/ggml-gpt4all-j.tmpl`. Works fine with no streaming:
```sh
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{ "model": "llama-2-7b-chat.ggmlv3.q4_0.bin", 
     "messages": [{"role": "user", "content": "Generate some sample text in English, followed by some sample text in Chinese."}],
     "temperature": 0.9 
   }'
```
```json
{"object":"chat.completion","model":"llama-2-7b-chat.ggmlv3.q4_0.bin","choices":[{"message":{"role":"assistant","content":"Sure! Here's a sample text in English:\n\"The sun was shining brightly as I walked through the park. The birds were singing their sweet melodies and the flowers were blooming beautifully. It was a peaceful and serene atmosphere, perfect for a relaxing stroll.\"\nAnd here's a sample text in Chinese:\n「太阳照亮了我在公园散步。鸟儿唱着美妙的歌声，花卉也开始 цвет。这是一个和谐的环境，非常适合休息散步。」\nPlease let me know if you have any other questions or requests!"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}
```
but if I do the same message over [ChatWizard](https://github.com/lisiur/ChatWizard), it cuts off:

> Sure! Here's a sample text in English:
> "The sun was shining brightly as I walked through the park. The birds were singing their sweet melodies and the flowers were blooming beautifully. It was a peaceful and serene atmosphere, perfect for a relaxing stroll."
> And here's a sample text in Chinese:

with error message `Error rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8`.
> 「太阳

**Comment by jayagami** [comment]
I have tested CJK inputs on the ChatGPT Next Web, still get  damaged code.
https://github.com/Yidadaa/ChatGPT-Next-Web

**Comment by yantoz** [comment]
The following quick and dirty hack seems to fix it. Basically, appending byte by byte until a code point is achieved before calling tokenCallback.

```
diff --git a/api/backend/llm.go b/api/backend/llm.go
index 01b3eb1..9714d95 100644
--- a/api/backend/llm.go
+++ b/api/backend/llm.go
@@ -6,6 +6,7 @@ import (
        "regexp"
        "strings"
        "sync"
+       "unicode/utf8"
 
        config "github.com/go-skynet/LocalAI/api/config"
        "github.com/go-skynet/LocalAI/api/options"
@@ -97,9 +98,18 @@ func ModelInference(ctx context.Context, s string, loader *model.ModelLoader, c
 
                if tokenCallback != nil {
                        ss := ""
+                       buf := []byte{}
                        err := inferenceModel.PredictStream(ctx, opts, func(s []byte) {
-                               tokenCallback(string(s), tokenUsage)
-                               ss += string(s)
+                               for len(s) > 0 {
+                                       buf = append(buf, s[0])
+                                       s = s[1:]
+                                       r, _ := utf8.DecodeRune(buf)
+                                       if r != utf8.RuneError {
+                                               tokenCallback(string(buf), tokenUsage)
+                                               ss += string(buf)
+                                               buf = []byte{}
+                                       }
+                               }
                        })
```

**Comment by samm81** [comment]
after consulting the oracle (chatgpt) it seems like this maybe is the best way to handle this? I went ahead and put together a PR (#981)

I don't mean to steal your thunder @yantoz , if you want to make the PR I'll close mine in favor of yours, just wanted to get something out there

**Comment by yantoz** [comment]
@samm81 I am not familiar with Go but glad to hear you agree it is a solution. And please go ahead with your PR, I do not mind at all. Cheers!
