### ISSUE TITLE
error: llama: model does not exist gpt: model does not exist gpt2: model does not exist stableLM: model does not exist

### ISSUE THREAD

**Issue by limcheekin** [go-skynet/LocalAI#68]
Hi there,

First of all, I managed to compile the binary using `make build`, it produced an executable file `local-ai`. 

I started the local-ai using the following command:
```
./local-ai --f16 true --debug true --threads 2 --models-path ./models --context-size 2048
```
The app is started properly in my Ubuntu linux machine with the following screen:
```
 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.42.0                                   
 │               http://127.0.0.1:8080                            
 │       (bound on host 0.0.0.0 and port 8080)        
 │                                                                            
 │ Handlers ............ 10  Processes ........... 1  
 │ Prefork ....... Disabled  PID ............. 31788 
 └───────────────────────────────────────────────────┘
``` 
For your information, there's only one model file in the `./models` directory: `ggml-gpt4all-j.bin`

However, when I send the following request to the endpoint:
```
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
        "model": "ggml-gpt4all-j.bin",            
        "prompt": "What is Flutter?",
        "temperature": 0.7
}'
```

It send me the following response:
```
{"error":"llama: model does not exist gpt: model does not exist gpt2: model does not exist stableLM: model does not exist"}
```

May I know what did I missed? How do I find out what's wrong.
Let me know if you need more information.

Please advise. Thank you.

**Comment by normen** [comment]
It seems none of the loaders can load your model.. Also, a chat completion request doesn't have a "prompt", it has a "messages" array of objects with role/content fields, but I don't think thats the issue here.

**Comment by limcheekin** [comment]
Thanks for reply. Just find out there are two endpoints.

I tried with the `http://localhost:8080/v1/completions` endpoint, the same error persist.

**Comment by Aisuko** [comment]
Hi,guys. Now we migrate to support to use model gallery. And here is the example that support check if the model was loaded correctly. https://localai.io/basics/getting_started/

Thanks for your feedback, and I will close this issue. If the issue still occurred please reopen it.
