### ISSUE TITLE
Crash on Apple Silicon M1

### ISSUE THREAD

**Issue by outermind-ai** [go-skynet/LocalAI#687]
**LocalAI version:**
Latest,from master

**Environment, CPU architecture, OS, and Version:**
MacOS 12.6

**Describe the bug**
built successfully for Metal after adding gpu_layers: 1 ad f16: true to docker compose yaml, per the Readme but it said ld: warning: object file (/.../LocalAI/go-ggml-transformers/libtransformers.a(ggml.o)) was built for newer macOS version (12.6) than being linked (12.0)

**To Reproduce**
Follow instructions for Mac and build for metal then run, per the Readme

**Expected behavior**
Non-metal version worked fine but metal version crashes every time upon receiving request

**Logs**

LocalAI % ./local-ai --models-path ./models/ --debug
Starting LocalAI using 4 threads, with models path: ./models/
unexpected end of JSON input

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.47.0                   │ 
 │               http://127.0.0.1:8080               │ 
 │       (bound on host 0.0.0.0 and port 8080)       │ 
 │                                                   │ 
 │ Handlers ............ 32  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ............. 95353 │ 
 └───────────────────────────────────────────────────┘ 

3:08AM DBG Request received: {"model":"ggml-gpt4all-j","file":"","language":"","response_format":"","size":"","prompt":null,"instruction":"","input":null,"stop":null,"messages":[{"role":"user","content":"How are you?"}],"stream":false,"echo":false,"top_p":0,"top_k":0,"temperature":0.9,"max_tokens":0,"n":0,"batch":0,"f16":false,"ignore_eos":false,"repeat_penalty":0,"n_keep":0,"mirostat_eta":0,"mirostat_tau":0,"mirostat":0,"frequency_penalty":0,"tfz":0,"seed":0,"mode":0,"step":0,"typical_p":0}
3:08AM DBG Parameter Config: &{OpenAIRequest:{Model:ggml-gpt4all-j File: Language: ResponseFormat: Size: Prompt:<nil> Instruction: Input:<nil> Stop:<nil> Messages:[] Stream:false Echo:false TopP:0.7 TopK:80 Temperature:0.9 Maxtokens:512 N:0 Batch:0 F16:false IgnoreEOS:false RepeatPenalty:0 Keep:0 MirostatETA:0 MirostatTAU:0 Mirostat:0 FrequencyPenalty:0 TFZ:0 Seed:0 Mode:0 Step:0 TypicalP:0} Name: StopWords:[] Cutstrings:[] TrimSpace:[] ContextSize:512 F16:false NUMA:false Threads:4 Debug:true Roles:map[] Embeddings:false Backend: TemplateConfig:{Completion: Chat: Edit:} MirostatETA:0 MirostatTAU:0 Mirostat:0 NGPULayers:0 MMap:false MMlock:false LowVRAM:false TensorSplit: MainGPU: ImageGenerationAssets: PromptCachePath: PromptCacheAll:false PromptCacheRO:false PromptStrings:[] InputStrings:[] InputToken:[]}
3:08AM DBG Template found, input modified to: The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
### Prompt:
How are you?
### Response:

3:08AM DBG Loading model 'ggml-gpt4all-j' greedly
3:08AM DBG [llama] Attempting to load
3:08AM DBG Loading model llama from ggml-gpt4all-j
3:08AM DBG Loading model in memory from file: models/ggml-gpt4all-j
llama.cpp: loading model from models/ggml-gpt4all-j
error loading model: unexpectedly reached end of file
llama_load_model_from_file: failed to load model
3:08AM DBG [llama] Fails: failed loading model
3:08AM DBG [gpt4all] Attempting to load
3:08AM DBG Loading model gpt4all from ggml-gpt4all-j
3:08AM DBG Loading model in memory from file: models/ggml-gpt4all-j
zsh: killed     ./local-ai --models-path ./models/ --debug

**Comment by logancyang** [comment]
@outermind-ai where did it say to use 4-bit-quantized model? I can't even get the example to run on my M1.
