### ISSUE TITLE
OPTIONS /v1/chat/completions returns 405

### ISSUE THREAD

**Issue by yarray** [go-skynet/LocalAI#710]
**LocalAI version:** 3829aba

**Environment, CPU architecture, OS, and Version:** docker in WSL2

**Describe the bug**

When requesting OPTIONS /v1/chat/completions, the service returns 405. It would be better to return meaningful response since many ChatGPT clients request it. ChatNextWeb and ChatBox are two examples.

**To Reproduce**

1. Run LocalAI service
2. Install and run [ChatNextWeb](https://github.com/Yidadaa/ChatGPT-Next-Web)
3. Change "Endpoint" in settings to http://localhost:8080 and try to ask some questions.
4. The client will report the following:

```json
{
  "error": true,
  "message": "Failed to fetch"
}
```

5. Check the log of LocalAI, will see:

`405  -  OPTIONS  /v1/chat/completions`

**Expected behavior**

Returns 200. Tested clients work.

**Logs**

2023-07-02 00:47:11 [172.29.0.1]:45216  405  -  OPTIONS  /v1/chat/completions
2023-07-02 00:47:11 [172.29.0.1]:45216  405  -  OPTIONS  /v1/chat/completions
2023-07-02 00:47:18 [172.29.0.1]:45216  405  -  OPTIONS  /v1/chat/completions
2023-07-02 00:47:18 [172.29.0.1]:45216  405  -  OPTIONS  /v1/chat/completions
2023-07-02 00:47:18 [172.29.0.1]:45216  405  -  OPTIONS  /v1/chat/completions

**Additional context**

The "issue" is a bit tricky and may not be considered as a bug since OpenAI specification did not report OPTIONS. However, it would be very beneficial practically since the service will seamlessly connect to quite some clients for ChatGPT with the OPTIONS response.

**Comment by yarray** [comment]
> Yes, this is necessary for many software made with web technologies.
> 
> Those software are essentially web browsers, which (as a CORS security feature) sends a "preflight" request with method `OPTIONS` before every `POST`, `GET`, etc., request.
> 
> See [this StackOverflow discussion](https://stackoverflow.com/questions/38375124/what-is-the-reason-behind-using-option-request-before-post-on-cors-requests).
> 
> In the webdev world, it's implied that if an endpoint supports `POST`/`GET`/..., it also supports `OPTIONS`, so even though `OPTIONS` wasn't written on [OpenAI's API documentation](https://platform.openai.com/docs/api-reference/completions), we should still implement it.
> 
> EDIT: I see that we are using `gofiber` in this project. Maybe this will help: https://docs.gofiber.io/api/middleware/cors/

Thanks for your valuable comment. After viewing the gofiber docs and the source code of LocalAI, I found that given CORS=true in docker-compose or ./local-ai --cors will solve the problem and the service will accept OPTIONS. Now ChatGPT clients like Chat-Next-Web can work like charm.

Thank you for your invaluable comment. Having reviewed the gofiber documentation and examined the source code of LocalAI, I have discovered that setting `CORS=true` in the docker-compose file or running `./local-ai --cors` resolves the issue, allowing the service to accept OPTIONS requests. ChatGPT clients such as ChatGPT-Next-Web can now operate seamlessly.

Will close the issue. Perhaps the documentation can be improved in the future.

**Comment by SamirSaidani** [comment]
@yarray I suggest that ./local-ai should be cors enabled by default, instead of disable it by default. 

./local-ai --disable-cors to set it false, else it's true.

Would save a lot of time for people looking why the client they're using doesn't work.
