### ISSUE TITLE
SemVER tag releases for images.

### ISSUE THREAD

**Issue by xstar97** [go-skynet/LocalAI#727]
**Is your feature request related to a problem? Please describe.**
https://quay.io/repository/go-skynet/local-ai?tab=tags
there's a lot of images to choose from and they dont follow a semVER tag cycle like you do on github.

**Describe the solution you'd like**
A clearer image cycle release with semVER tags that match the tag release.

**Describe alternatives you've considered**
Not using master tags....

**Additional context**

**Comment by Aisuko** [comment]
Hi, @xstar97 thank you, good point. I assumed we can open a discussion for this cc @mudler . I assume the docker tags are easier for the developer to use currently, but we should make these tags more friendly to the users. Here is the docker tag strategy we have now.

https://github.com/go-skynet/LocalAI/blob/a6839fd23827672aeab5988b344a2a34d7e44e6a/.github/workflows/image.yml#L21-L58C1

**Comment by mudler** [comment]
they do follow semver. For each release on github there is a corresponding tag available: go-skynet/local-ai:v1.20.1

**Comment by xstar97** [comment]
> they do follow semver. For each release on github there is a corresponding tag available: go-skynet/local-ai:v1.20.1. Search for v, or v1.20
yes you have tag releases on github...i was referring to GHCR to release on that....but your images dont have a semver tag in quay, only a master and sha tag.
https://quay.io/repository/go-skynet/local-ai?tab=tags&tag=latest
