### ISSUE TITLE
Startup localai on linux boot

### ISSUE THREAD

**Issue by thawkins** [go-skynet/LocalAI#762]
I can startup localai use docker-compose, but it is manual. Is it possible to supply a systemd unit file to start it up on boot? 

I would like my server that has localai on it to boot with the api enabled. If it restarts

rc.local script, but its not portable

**Additional context**

**Comment by Aisuko** [comment]
As you mentioned `systemd`, I believe you can create a `systemed` service configuration for the `docker-compose`. Here is an example https://gist.github.com/mosquito/b23e1c1e5723a7fd9e6568e5cf91180f
