### ISSUE TITLE
Transport error when connecting

### ISSUE THREAD

**Issue by apcameron** [go-skynet/LocalAI#765]
4:07PM DBG no galleries to load
4:07PM INF Starting LocalAI using 4 threads, with models path: /home/andrew/Downloads/LocalAI/models
4:07PM INF LocalAI version: v1.21.0 (fb6cce487fb53d9de1c1a6b3414261f52b5cdbe0)

<pre>
<font color="#5E5C64"> ┌───────────────────────────────────────────────────┐ </font>
<font color="#5E5C64"> │                   </font><font color="#33C7DE">Fiber v2.48.0</font><font color="#5E5C64">                   │ </font>
<font color="#5E5C64"> │               http://127.0.0.1:8080               │ </font>
<font color="#5E5C64"> │       (bound on host 0.0.0.0 and port 8080)       │ </font>
<font color="#5E5C64"> │                                                   │ </font>
<font color="#5E5C64"> │ Handlers ............ </font><font color="#33C7DE">31</font><font color="#5E5C64">  Processes ........... </font><font color="#33C7DE">1</font><font color="#5E5C64"> │ </font>
<font color="#5E5C64"> │ Prefork ....... Disabled  PID ............ </font><font color="#33C7DE">321830</font><font color="#5E5C64"> │ </font>
<font color="#5E5C64"> └───────────────────────────────────────────────────┘</font> </pre>

rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:37991: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:46395: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:35147: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:43099: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:39539: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:33573: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:34853: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp [::1]:33901: connect: connection refused"

**Comment by apcameron** [comment]
Resolved by updating my model. It seems it was too old

**Comment by galfrylich** [comment]
which model did you use?

**Comment by rdctmeconomou** [comment]
After enabling debug mode, I got this error when LocalAI tried to load the model because the absolute path to the back end had a space in it.  Looking at run.sh, it seems that none of the environment variables are quoted, which is pretty bad practice.  If I have the time and energy, I'm going to hunt down the source repos and file some pull requests.

```
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr ++ dirname '/Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp/run.sh'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + CURDIR='/Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + cd /
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + echo 'CPU info:'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stdout CPU info:
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + grep -e 'model\sname' /proc/cpuinfo
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + head -1
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr grep: /proc/cpuinfo: No such file or directory
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + grep -e flags /proc/cpuinfo
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + head -1
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr grep: /proc/cpuinfo: No such file or directory
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + BINARY=llama-cpp-fallback
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + grep -q -e '\savx\s' /proc/cpuinfo
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr grep: /proc/cpuinfo: No such file or directory
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + grep -q -e '\savx2\s' /proc/cpuinfo
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr grep: /proc/cpuinfo: No such file or directory
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + grep -q -e '\savx512f\s' /proc/cpuinfo
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr grep: /proc/cpuinfo: No such file or directory
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + '[' -n '' ']'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr ++ uname
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + '[' Darwin == Darwin ']'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + export 'DYLD_LIBRARY_PATH=/Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp/lib:'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + DYLD_LIBRARY_PATH='/Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp/lib:'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + '[' -f /Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp/lib/ld.so ']'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr run.sh: line 52: [: /Users/username/Library/Application: binary operator expected
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + echo 'Using binary: llama-cpp-fallback'
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stdout Using binary: llama-cpp-fallback
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr + exec /Users/username/Library/Application Support/LocalAI/backends/metal-llama-cpp/llama-cpp-fallback --addr 127.0.0.1:60885
2:31PM DBG GRPC(qwen2.5-coder-32b-instruct-127.0.0.1:60885): stderr run.sh: line 59: /Users/username/Library/Application: No such file or directory
```
