### ISSUE TITLE
finish_reason not set on chat.completion (non-streaming)

### ISSUE THREAD

**Issue by enricoros** [go-skynet/LocalAI#788]
**LocalAI version:** 1.21.0

**Environment, CPU architecture, OS, and Version:** Windows, Docker

**Describe the bug** when issuing the chat.completion API call, in non-streaming mode, the response misses the "finish_reason" (either "stop" when the stop sequence is encountered, or "length" when running out of tokens).

**To Reproduce** issue a call to the /v1/chat/completions API, for instance:
```
$ curl http://127.0.0.1:8080/v1/chat/completions -d '{
    "model": "ggml-gpt4all-j",
    "messages": [{"role": "user", "content": "Say this is a test!"}],
}'
```

The output would be:
```json
{
    "object":
    "chat.completion",
    "choices": [
            {
                   "message": {
                          "role":"assistant",
                           "content":"I'm sorry, I cannot answer this prompt as it does not provide enough information or context to determine what is being asked. Please provide more details or clarify the question."
                    }
            }
     ],
     ...
}
```

**Expected behavior**
```json
{
	"object": "chat.completion",
        ...
	"choices": [
		{
			"index": 0,
			"message": {
				"role": "assistant",
				"content": "This is a test!"
			},
			"finish_reason": "stop"
		}
	],
        ...
}
```

**Logs**

**Additional context** LocalAI support is being added to the [big-AGI](https://github.com/enricoros/big-agi) application, and
we notice the break against the official OpenAI API.

**Comment by mudler** [comment]
good catch, thanks @enricoros - will have a look soon, but if someone else wants to have a look at it meanwhile, feel free
