### ISSUE TITLE
API endpoint documentation link broken.

### ISSUE THREAD

**Issue by johngoad** [go-skynet/LocalAI#789]
**LocalAI version:**

**Environment, CPU architecture, OS, and Version:**

404

**Describe the bug**
Broken link to API endpoints reference in the README file

**To Reproduce**
Link never resolves just a blank white page... can be reproduced by clicking on the link.
**Expected behavior**
List of available endpoints.
**Logs**
![Screenshot 2023-07-21 at 9 48 08 AM](https://github.com/go-skynet/LocalAI/assets/22306300/5feffb03-0bed-47c3-aeeb-26617c685fe4)

**Additional context**

Great project, having trouble getting it working on a Mac as most of the documentation is written for Docker. Yeah, it is my personal problem... but it sure would be cool to have more information.

**Comment by mudler** [comment]
Fixed now, thanks!
