### ISSUE TITLE
能否增加根据模型，直接调用openai的接口？

### ISSUE THREAD

**Issue by vual** [go-skynet/LocalAI#795]
是这样，我有个项目，有些需要调用openai的chatgpt接口，有些需要调本地模型接口，而我只想填一个地址。
这个项目能否增加根据模型，比如我传gpt-3.5，就直接指向openai的接口地址？

**Comment by Aisuko** [comment]
Hi @vual. It looks like this feature may not in the roadmap. So, I close this issue now. Please feel free to open discussion
