### ISSUE TITLE
reported model list includes ".DS_Store"

### ISSUE THREAD

**Issue by rozek** [go-skynet/LocalAI#801]
**LocalAI version:**
master version from July 25th, commit 12fe093

**Environment, CPU architecture, OS, and Version:**
Docker build on Macbook Air M2, macos Ventura 13.4.1

**Describe the bug**
`curl http://localhost:8080/v1/models`

reports

`{"object":"list","data":[{"id":".DS_Store","object":"model"},{"id":"llama-2-13b.ggmlv3.q4_0.bin","object":"model"},{"id":"llama-2-13b.ggmlv3.q4_0","object":"model"}]}`

which includes `.DS_Store`, an internal file used by macos.

Perhaps, "hidden" files (i.e., those starting with a `.`), should be excluded in general

**Comment by rozek** [comment]
wow - how cool is that!? I'll try these suggestions in a minute...

**Comment by rozek** [comment]
just to report my progress: I could not use the "excludes" trick since my local docker build did not properly mount the external folder until I explicitly specified it in the `docker run` command - and there, the "excludes" trick is not available.

Obviously, deleting the `.DS_Store` file is also not possible...

**Comment by dave-gray101** [comment]
This was fixed in #830 , closing.
