### ISSUE TITLE
create blog/docs website

### ISSUE THREAD

**Issue by mudler** [go-skynet/LocalAI#93]

**Comment by Aisuko** [comment]
hi @mudler, I'd like to contribute to this one. May you share more detail? Is the GitHub page(static website) ok?

**Comment by mudler** [comment]
hey @Aisuko that'd be great - yes gh-pages works for me. I've been using hugo so far and quite used to it, but I'm good as well with something equivalent.

I've bought already the localai.io domain, so just need to be linked to the repository

**Comment by Aisuko** [comment]
Thanks for your quick reply. @mudler Maybe I got your point. If I remember right the OSM-doc project is using Hugo. Maybe this is what you want? https://github.com/openservicemesh/osm-docs

**Comment by mudler** [comment]
docsy is very popular too, and quite quick to spin-up: https://github.com/google/docsy-example

**Comment by Aisuko** [comment]
> docsy is very popular too, and quite quick to spin-up: https://github.com/google/docsy-example

I know this one, it is cool. Let's do a quick move.
