### ISSUE TITLE
Add a compilation version for Windows.

### ISSUE THREAD

**Issue by byebye758** [go-skynet/LocalAI#961]
My reason is that I ran llama 13B in LocalAI, selected GPU for execution, and by default, it requires 25GB of memory. However, I currently only have a 24GB GPU. Based on my understanding, starting from Windows 10, it's possible to share a portion of system memory with GPU VRAM. This way, it could provide a more convenient way for most learners using LocalAI to conduct their learning tasks.

**Comment by Aisuko** [comment]
Hi, @byebye758, thanks for your feedback.

The GPU VRAM is separate from the system memory, and they cannot be shared.

**Comment by Aisuko** [comment]
I would like to close this issue. Feel free to open a new discussion in [Discussions](https://github.com/go-skynet/LocalAI/discussions) about this.
